dist: xenial  # required for Python >= 3.7
language: python
python:
  - "3.7"

git:
  quiet: true

install:
  - pip install pipenv
  - pipenv install --dev

script: 
  - pycodestyle $(git ls-files '*.py')
  - pydocstyle $(git ls-files '*.py')
  - pyflakes $(git ls-files '*.py')
  - ./manage.py makemigrations website
  - ./manage.py migrate
  - ./manage.py test
