dist: xenial  # required for Python >= 3.7
language: python
python:
  - "3.8"

git:
  quiet: true

install:
  - pip install pipenv
  - pipenv install --dev

script: 
  - flake8 --exclude=website/migrations/*.py,.git $(git ls-files '*.py')
  - ./manage.py makemigrations website
  - ./manage.py migrate
  - ./manage.py test
