# Generated by Django 3.0.6 on 2020-06-30 06:34

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('website', '0001_initial'), ('website', '0002_lightbox'), ('website', '0003_auto_20200525_1642'), ('website', '0004_auto_20200525_1700'), ('website', '0005_auto_20200609_1622'), ('website', '0006_auto_20200609_1626'), ('website', '0007_remove_customuser_number'), ('website', '0008_school_region'), ('website', '0009_auto_20200614_1608'), ('website', '0010_auto_20200614_2055'), ('website', '0011_auto_20200615_1635'), ('website', '0012_auto_20200615_1637'), ('website', '0013_auto_20200615_1639'), ('website', '0014_auto_20200615_1640'), ('website', '0015_auto_20200615_1641'), ('website', '0016_auto_20200615_1643'), ('website', '0017_auto_20200615_1646'), ('website', '0018_auto_20200630_1209'), ('website', '0019_auto_20200630_1216'), ('website', '0020_auto_20200630_1335'), ('website', '0021_auto_20200630_1336'), ('website', '0022_auto_20200630_1343')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(help_text='Users without the view_unreleased_event permission cannot see the event until start date and the event is released.')),
                ('finish_date', models.DateField()),
                ('slug', models.SlugField(default='event', help_text='The slug is the what appears in the URL. If you leave it as the default the slug will be autogenerated.')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(default='', null='')),
                ('display_image', models.ImageField(blank=True, default='', help_text='This field is optional. Please provide it if you are highlighting the event.', max_length=150, null=True, upload_to='uploads/%Y/%m/')),
                ('highlighted_event', models.BooleanField(default=False, help_text='Display this event on the homepage')),
                ('hidden_event', models.BooleanField(default=True, help_text='Users cannot view the event (including on the events feed)')),
                ('released', models.BooleanField(default=True, help_text='Leave this checked if you want to automatically release the event on the start date (at midnight).')),
            ],
            options={
                'permissions': [('view_hidden_event', 'Can view hidden events'), ('view_unreleased_event', 'Can view unreleased events')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='position name')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AS', 'Assigned'), ('WL', 'Waitlist'), ('DE', 'Decline')], max_length=2)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='website.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('location', models.CharField(max_length=100)),
                ('assigned', models.ManyToManyField(related_name='workshops_assigned', through='website.VolunteerAssignment', to='website.Volunteer')),
                ('available', models.ManyToManyField(related_name='workshops_available', to='website.Volunteer', verbose_name='available volunteers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='website.Event')),
            ],
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='website.Workshop'),
        ),
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_richtext_set', to='website.Event')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('number', models.CharField(max_length=15, verbose_name='phone number')),
                ('date_of_birth', models.DateField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_number', models.CharField(max_length=15, verbose_name="parent's phone number")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event')),
            ],
        ),
        migrations.CreateModel(
            name='NoEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('url', models.URLField(help_text='URL of a NoEmbed compatible URL e.g. YouTube link', max_length=150)),
                ('caption', models.CharField(help_text='Caption that appears with the embed.', max_length=150)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_noembed_set', to='website.Event')),
            ],
            options={
                'verbose_name': 'embed',
                'verbose_name_plural': 'embeds',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('name', models.CharField(help_text='Try to keep this short. It appears on the download button.', max_length=30)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_download_set', to='website.Event')),
            ],
            options={
                'verbose_name': 'download',
                'verbose_name_plural': 'downloads',
            },
        ),
        migrations.AlterUniqueTogether(
            name='volunteerassignment',
            unique_together={('workshop', 'volunteer')},
        ),
        migrations.CreateModel(
            name='LightBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('file', models.ImageField(max_length=150, upload_to='uploads/%Y/%m/')),
                ('caption', models.CharField(help_text='Alternate text for the image.', max_length=150)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_lightbox_set', to='website.Event')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='school name')),
                ('region', models.CharField(choices=[('AU_QLD', 'Queensland'), ('AU_NSW', 'New South Wales'), ('AU_SA', 'South Australia'), ('AU_NT', 'Northern Territory'), ('AU_VIC', 'Victoria'), ('AU_WA', 'Western Australia'), ('AU_TAS', 'Tasmania'), ('OT_NUL', 'Other - Unknown')], default='OT_NUL', max_length=6, verbose_name='wider govermental region')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.School')),
                ('email_consent', models.BooleanField(default=False)),
            ],
        ),
    ]
