# Generated by Django 3.0.6 on 2020-05-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_lightbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightbox',
            old_name='url',
            new_name='file',
        ),
    ]
