# Generated by Django 3.0.6 on 2020-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200525_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightbox',
            name='file',
            field=models.ImageField(max_length=150, upload_to='uploads/%Y/%m/'),
        ),
    ]
