# Generated by Django 3.0.6 on 2020-06-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200609_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number',
        ),
    ]
