# Generated by Django 3.0.6 on 2020-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('AU_QLD', 'Queensland'), ('AU_NSW', 'New South Wales'), ('AU_SA', 'South Australia'), ('AU_NT', 'Northern Territory'), ('AU_VIC', 'Victoria'), ('AU_WA', 'Western Australia'), ('AU_TAS', 'Tasmania'), ('OT_NUL', 'Other - Unknown')], default='OT_NUL', max_length=6, verbose_name='wider govermental region'),
        ),
    ]
