# Generated by Django 3.0.6 on 2020-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200614_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', null=''),
        ),
        migrations.AddField(
            model_name='event',
            name='display_image',
            field=models.ImageField(default='', max_length=150, null='', upload_to='uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='event',
            name='highlighted_event',
            field=models.BooleanField(default=False),
        ),
    ]
