# Generated by Django 3.0.6 on 2020-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200615_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
