# Generated by Django 3.0.6 on 2020-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200615_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_image',
            field=models.ImageField(blank=True, help_text='This field is optional. Please provide it if you are highlighting the event.', max_length=150, null=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='highlighted_event',
            field=models.BooleanField(default=False, help_text='Display this event on the homepage'),
        ),
    ]
