# Generated by Django 3.0.6 on 2020-06-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200630_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_hidden_event', 'Can view hidden events'), ('view_unreleased_event', 'Can view unreleased events')]},
        ),
    ]
