# Generated by Django 3.0.6 on 2020-06-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200630_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hidden_event',
            field=models.BooleanField(default=True, help_text='Users cannot view the event (including on the events feed)'),
        ),
    ]
