# Generated by Django 3.0.6 on 2020-06-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200630_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_hidden_event', 'Can view hidden events'), ('view_unreleased', 'Can view unreleased events')]},
        ),
    ]
